### ISSUE TITLE
Some Feedback

### ISSUE THREAD

**Issue by jeremydmiller** [webadvanced/Structuremap.MVC5#1]
Just 2 things, and I think the first one is nitpicking.
- In your IoC.Initialize(); I'd strongly suggest using a Container built from a separate Registry class. I'm trying to encourage folks to stop using the static ObjectFactory wrapper around Container if possible
- I might be missing where you did it, but you probably want to dispose the main application Container on application shutdown

**Comment by valmont** [comment]
Hey Jeremy, thanks for the feedback. I have updated the implementation, let me know if it's a pass.
